# Generated by Django 3.2 on 2025-07-04 21:01

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0004_aboutu_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurVishon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='OurMission')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='OurMission')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='OurMission')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
