# Generated by Django 3.2 on 2025-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apparel', '0007_navitem_siteinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientMessage',
        ),
        migrations.DeleteModel(
            name='ServiceContent',
        ),
        migrations.RenameField(
            model_name='leadership',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourmission',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourservice',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourvalue',
            old_name='image1',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='ourvision',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='aboutu',
            name='link',
        ),
        migrations.RemoveField(
            model_name='aboutu',
            name='number',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='leadership',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='ourgallery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='ourmission',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='ourservice',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='ourvalue',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='ourvalue',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='ourvision',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='ourvision',
            name='image3',
        ),
    ]
